services:
  web:
    image: nginx:alpine
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/conf.d:/etc/nginx/conf.d:ro
      - /etc/ssl/private/YOURPRIVATE.key:/etc/ssl/private/YUORPRIVATE.key:ro
      - /etc/ssl/certs/YOURPUBLIC.pem:/etc/ssl/certs/YOURPUBLIC.pem:ro
    ports:
      - "80:80"
      - "443:443"
    environment:
      - NGINX_PORT=80
    networks:
      - calendar_bot

  app:
    user: "1000:1000"
    build:
      context: ../../app
    volumes:
      - ../../app:/app
    env_file:
      - .env
    ports:
      - "8000:8000"
    networks:
      - calendar_bot
    command: python3 main.py

  bot:
    user: "1000:1000"
    build:
      context: ../../bot
    volumes:
      - ../../bot:/bot
      - /etc/ssl/certs/YOURPUBLIC.pem:/etc/ssl/certs/YOURPUBLIC.pem:ro
    env_file:
      - .env
    expose:
      - "8080"
    networks:
      - calendar_bot
    command: python3 main.py --webhook

  watcher:
    user: "1000:1000"
    build:
      context: ../../watcher
    volumes:
      - ../../watcher:/watcher
    env_file:
      - .env
    networks:
      - calendar_bot
    depends_on:
      - app
    restart: unless-stopped
    command: python3 main.py

networks:
  calendar_bot:
    name: calendar_bot
    external: false